---
title: "analysis"
author: "Arielle Herman"
date: "5/7/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
dy <- readRDS("data/output/dyad_year.rds")
dy
```

```{r include=FALSE}
dy_sub <- dy %>% select(-dispnum, -log_pec, -pec_bi) %>% mutate(democ = dyadtype == "democ") %>% na.omit()

no_taw <- dy_sub %>% mutate(taw = if_all(c(ccode1, ccode2), ~ . %in% c(713, 710)),
                        no_taw = ifelse(taw, FALSE, homogenous),
                        dyadtype2 = ifelse(taw, "mixed", dyadtype))

no_taw %>% filter(taw)

log1 <- glm(mid ~ homogenous + majpow + cont + allied + majpow + relpow + pec_bi_lag,
            data = no_taw, family = "binomial")
summary(log1)

log2 <- glm(mid ~ no_taw + majpow + cont + allied + majpow + relpow + pec_bi,
            data = no_taw, family = "binomial")

log3 <- glm(mid ~ autoc + democ + majpow + cont + allied + majpow + relpow + pec_bi,
            data = no_taw, family = "binomial")

log4 <- glm(mid ~ dyadtype + majpow + cont + allied + majpow + relpow + pec_bi,
            data = no_taw, family = "binomial")

no_taw %>% filter(!autoc, !democ) %>% count(dyadtype)
```

```{r results='asis', echo=FALSE}
stargazer::stargazer(list(log1, log2, log3, log4), type = "latex", title = "Regression Results", header = FALSE)
```

```{r eval = F, include=F}
undirected <- dy_sub %>% select(-log_pec, -lapse) %>% na.omit %>% filter(ccode1 < ccode2)
log5 <- glm(mid ~ majpow + allied + relpow + autoc + democ + cont, data = undirected)
summary(log3)

no_taw %>% filter(homogenous, no_taw)



```