# metadata
# file:///C:/Users/ariel/OneDrive/4-SP22/2_Auth/data/MID%205%20Data%20and%20Supporting%20Materials/MID%205.0%20Codebook.pdf
metadata <- tribble(~col, ~labels, ~label,
                    "sidea", c("yes" = 1, "no" = 0), "the side that contains the state (or states) that first crossed the threat-display-use of force threshold",
                    "revstate", c("yes" = 1,
                                  "no" = 0), "state that demonstrates a desire to change the status quo in a significantway",
                    "revtype1", c("not applicable" = 0,
                                  "territory" = 1,
                                  "policy" = 2,
                                  "regime/government" = 3,
                                  "other" = 4,
                                  "missing" = NA), "type of revisions sought by that state",
                    "revtype2", c("not applicable" = 0,
                                  "territory" = 1,
                                  "policy" = 2,
                                  "regime/government" = 3,
                                  "other" = 4,
                                  "missing" = NA), "type of revisions sought by that state",
                    "hostlev", c("no militarized action" = 1,
                                 "threat to use force" = 2,
                                 "display of force" = 3,
                                 "use of force" = 4,
                                 "war" = 5), "hostility level reached by state in dispute",
                    "orig", c("yes" = 1,
                              "no" = 0),"originator of dispute",
                    "hiact", c("No militarized action [1]" = 0,
                               "Threat to use force [2]" = 1,
                               "Threat to blockade [2]" = 2,
                               "Threat to occupy territory [2]" = 3,
                               "Threat to declare war [2]" = 4,
                               "Threat to use CBR weapons [2]" = 5,
                               "Threat to join war [2]" = 6,
                               "Show of force [3]" = 7,
                               "Alert [3]" = 8,
                               "Nuclear alert [3]" = 9,
                               "Mobilization [3]" = 10,
                               "Fortify border [3]" = 11,
                               "Border violation [3]" = 12,
                               "Blockade [4]" = 13,
                               "Occupation of territory [4]" = 14,
                               "Seizure [4]" = 15,
                               "Attack [4]" = 16,
                               "Clash [4]" = 17,
                               "Declaration of war [4]" = 18,
                               "Use of CBR weapons [4]" = 19,
                               "Begin interstate war [5]" = 20,
                               "Join interstate war [5]" = 21, 
                               "Missing [NA]" = NA), "highest action by state in dispute [bracketed numbers refer to corresponding hostility level]")


st_auth_codes <- c("interruption" = -66,
                   "interregnum" = -77,
                   "transition" = -88)
pol_metadata <-
  tribble(~col, ~labels, ~label,
          "flag", c("confident" = 0,
                    "tentative" = 1,
                    "tenuous" = 2), "coders’ general confidence in the component variable scores assigned during a Polity annual update",
          "fragment", c("no overt fragmentation" = 0,
                        "slight fragmentation" = 1,
                        "moderate fragmentation" = 2,
                        "serious fragmentation" = 3), "the operational existence of a separate polity, or polities, comprising substantial territory and population within the recognized borders of the state and over which the coded polity exercises no effective authority",
          "xrreg", c("unregulated" = 1,
                     "designational/transitional" = 2,
                     "regulated" = 3,
                     st_auth_codes), "regulation of chief executive recruitment",
          "xrcomp", c("selection" = 1,
                      "dual/transitional" = 2,
                      "election" = 3,
                      st_auth_codes), "competitiveness of executive recruitment",
          "xropen", c("closed" = 1,
                      "dual executive-designation" = 2,
                      "dual executive-election" = 3,
                      "open" = 4,
                      st_auth_codes), "openness of executive recruitment",
          "xconst", c("unlimited authority" = 1,
                      "intermediate category: 2" = 2,
                      "slight to moderate limitation" = 3,
                      "intermediate category: 4" = 4,
                      "substantial limitations" = 5,
                      "intermediate category: 6" = 6,
                      "executive parity or subordination" = 7,
                      st_auth_codes), "executive constraints (decision rules)",
          "parreg", c("unregulated" = 1,
                      "multiple identity" = 2,
                      "sectarian" = 3,
                      "restricted" = 4,
                      "regulated" = 5,
                      st_auth_codes), "regulation of participation",
          "parcomp", c("not applicable" = 0,
                       "repressed" = 1,
                       "suppressed" = 2,
                       "factional" = 3,
                       "transitional" = 4,
                       "competitive" = 5,
                       st_auth_codes), "competitiveness of participation",
          "polcomp", c("suppressed" = 1,
                       "restricted" = 2,
                       "imposed transition" = 3,
                       "uninstitutionalized" = 4,
                       "gradual transition" = 5,
                       "factional/restricted" = 6,
                       "factional" = 7,
                       "electoral transition: persistent conflict" = 8,
                       "electoral transition: limited conflict" = 9,
                       "institutionalized electoral" = 10), "concept variable composed of parreg and parcomp as per table 3.2 in codebook",
          "eprec", c("exact" = 1,
                     "assigned" = 2,
                     "approximate" = 3,
                     "missing" = 4,
                     "unknown" = 9), "end date precision",
          "bprec", c("exact" = 1,
                     "assigned" = 2,
                     "approximate" = 3,
                     "missing" = 4,
                     "unknown" = 9), "begin date precision")

# http://svmiller.com/peacesciencer/reference/cow_contdir.html
cow_metadata <- tribble(~col, ~labels, ~label,
                        "conttype", c("direct land contiguity" = 1,
                                "separated by 12 miles of water or fewer" = 2,
                                "separated by 24 miles of water or fewer" = 3,
                                "separated by 150 mildes of water or fewer" = 4,
                                "separated by 400 miles of water or fewer" = 5), "Correlates of War direct contiguity data")


